/**
 * schemas/*.schema.json -> generated/zod/<name>.ts
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { emitZodModule, type JsonSchema } from "./jsonschema-to-zod.ts";

const root = resolve(import.meta.dirname, "..");
const schemasDir = join(root, "schemas");
const outDir = join(root, "generated", "zod");
mkdirSync(outDir, { recursive: true });

const names: string[] = [];
for (const file of readdirSync(schemasDir).sort()) {
  if (!file.endsWith(".schema.json")) continue;
  const name = basename(file, ".schema.json");
  const doc = JSON.parse(readFileSync(join(schemasDir, file), "utf8")) as JsonSchema;
  const code = emitZodModule(doc, {
    typesModule: `../typescript/${name}.ts`,
    banner: [`Generated by tools/generate-zod.ts from schemas/${file}. Do not edit.`, `${doc.title ?? ""}`.trim()].filter(Boolean),
  });
  writeFileSync(join(outDir, `${name}.ts`), code);
  names.push(name);
  console.log(`generated/zod/${name}.ts`);
}

const index = [
  "// Generated by tools/generate-zod.ts. Do not edit.",
  ...names.map((n) => `export * as ${n.replace(/-(\w)/g, (_, c: string) => c.toUpperCase())} from "./${n}.ts";`),
  "",
].join("\n");
writeFileSync(join(outDir, "index.ts"), index);
console.log("generated/zod/index.ts");
