/**
 * schemas/*.schema.json -> generated/typescript/<name>.ts (plain TypeScript types).
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { compile, type JSONSchema } from "json-schema-to-typescript";

const root = resolve(import.meta.dirname, "..");
const schemasDir = join(root, "schemas");
const outDir = join(root, "generated", "typescript");
mkdirSync(outDir, { recursive: true });

/**
 * Adapt the 2020-12 schemas to json-schema-to-typescript's draft-07 dialect so
 * the emitted types line up with the Zod schemas generated from the same file.
 */
function adaptForJsonSchemaToTypescript(schema: unknown): unknown {
  if (Array.isArray(schema)) return schema.map(adaptForJsonSchemaToTypescript);
  if (!schema || typeof schema !== "object") return schema;
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(schema as Record<string, unknown>)) out[key] = adaptForJsonSchemaToTypescript(value);
  if (Array.isArray(out.prefixItems)) {
    out.items = out.prefixItems;
    delete out.prefixItems;
    out.additionalItems = false;
  } else if (out.type === "array") {
    // minItems/maxItems would otherwise become fixed-length tuple types, which
    // the Zod schemas (z.array().min()) cannot be assigned to. Keep them as
    // runtime constraints only.
    delete out.minItems;
    delete out.maxItems;
  }
  const constraintKeys = Object.keys(out).filter((k) => !["description", "title", "default"].includes(k) && !k.startsWith("x-"));
  if (constraintKeys.length === 0) out.tsType = "unknown"; // an unconstrained schema is `unknown`, not `{}`
  return out;
}

const names: string[] = [];
for (const file of readdirSync(schemasDir).sort()) {
  if (!file.endsWith(".schema.json")) continue;
  const name = basename(file, ".schema.json");
  const schema = adaptForJsonSchemaToTypescript(JSON.parse(readFileSync(join(schemasDir, file), "utf8"))) as JSONSchema;
  // json-schema-to-typescript names the root after `title`; give it a stable identifier instead.
  const rootName = `${name.replace(/(^|-)(\w)/g, (_, __, c: string) => c.toUpperCase())}Root`;
  let ts: string;
  try {
      // A root-level $ref next to $defs trips json-schema-to-typescript's ref
    // resolver; `allOf: [{$ref}]` yields the same alias and keeps every $def.
    const { $ref: rootRef, ...rest } = schema;
    const input: JSONSchema = rootRef ? { ...rest, title: rootName, allOf: [{ $ref: rootRef }] } : { ...schema, title: rootName };
    ts = await compile(input, rootName, {
    bannerComment: `/* Generated by tools/generate-types.ts from schemas/${file}. Do not edit. */`,
    additionalProperties: false,
    strictIndexSignatures: false,
    unreachableDefinitions: true,
    declareExternallyReferenced: true,
    style: { printWidth: 110, singleQuote: false },
    });
  } catch (error) {
    console.error(`FAILED ${file}: ${String((error as Error).message).slice(0, 300)}`);
    process.exitCode = 1;
    continue;
  }
  writeFileSync(join(outDir, `${name}.ts`), ts);
  names.push(name);
  console.log(`generated/typescript/${name}.ts`);
}

const index = [
  "// Generated by tools/generate-types.ts. Do not edit.",
  ...names.map((n) => `export type * as ${n.replace(/-(\w)/g, (_, c: string) => c.toUpperCase())} from "./${n}.ts";`),
  "",
].join("\n");
writeFileSync(join(outDir, "index.ts"), index);
console.log("generated/typescript/index.ts");
